name: Basic Workflow

on: [push]  # Triggers on any push to any branch

jobs:
  print-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print Info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        python --version
        ls -la
